# Generated by Django 3.2.12 on 2023-08-07 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VipCard',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除')),
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, help_text='会员卡名称', max_length=20, null=True, verbose_name='会员卡名称')),
                ('vipType', models.CharField(blank=True, help_text='VIP类型', max_length=20, null=True, verbose_name='VIP类型')),
                ('sort', models.IntegerField(blank=True, help_text='排序', null=True, verbose_name='排序')),
                ('discount', models.IntegerField(blank=True, default=0, help_text='折扣', null=True, verbose_name='折扣')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='购买金额', max_digits=5, max_length=10, null=True, verbose_name='购买金额')),
                ('isRecommend', models.IntegerField(blank=True, default=0, help_text='是否推荐', null=True, verbose_name='是否推荐')),
                ('status', models.IntegerField(blank=True, default=0, help_text='状态', null=True, verbose_name='状态')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '会员卡配置表',
                'verbose_name_plural': '会员卡配置表',
                'db_table': 'admin_vip_card',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='UserVipCard',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除')),
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('status', models.IntegerField(blank=True, default=0, help_text='状态', null=True, verbose_name='状态')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='关联用户', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_vip_card', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
                ('vipCard', models.ForeignKey(blank=True, db_constraint=False, help_text='关联会员卡配置', null=True, on_delete=django.db.models.deletion.PROTECT, to='client.vipcard', verbose_name='关联会员卡配置')),
            ],
            options={
                'verbose_name': '用户会员卡',
                'verbose_name_plural': '用户会员卡',
                'db_table': 'admin_user_vip_card',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='UserAddr',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除')),
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('addr', models.CharField(help_text='用户地址', max_length=100, null=True, verbose_name='用户地址')),
                ('isDefault', models.IntegerField(blank=True, default=1, help_text='是否默认', null=True, verbose_name='是否默认')),
                ('status', models.IntegerField(blank=True, default=0, help_text='状态', null=True, verbose_name='状态')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='关联用户', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_addr', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'admin_user_addr',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
