# Generated by Django 3.2.12 on 2023-08-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservipcard',
            name='expiration',
            field=models.DateTimeField(auto_now=True, help_text='过期时间', null=True, verbose_name='过期时间'),
        ),
    ]
