# Generated by Django 3.2.12 on 2023-08-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_uservipcard_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservipcard',
            name='isExpired',
            field=models.IntegerField(blank=True, default=0, help_text='是否到期', null=True, verbose_name='是否到期'),
        ),
    ]
