# Generated by Django 3.2.12 on 2023-08-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_uservipcard_isexpired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservipcard',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='uservipcard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservipcard',
            name='vipCard',
        ),
        migrations.RemoveField(
            model_name='vipcard',
            name='creator',
        ),
        migrations.DeleteModel(
            name='UserAddr',
        ),
        migrations.DeleteModel(
            name='UserVipCard',
        ),
        migrations.DeleteModel(
            name='VipCard',
        ),
    ]
