# Generated by Django 3.2.12 on 2023-07-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='apiwhitelist',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='area',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='dept',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='filelist',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='menubutton',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='messagecenter',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='messagecentertargetuser',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
    ]
